export const restaurantList = [
  {
    type: "restaurant",
    data: {
      id: "33456",
      name: "KFC",
      cloudinaryImageId: "bcdfefff",
      cusines: ["Burgers", "Biryani", "Fast Food", "SAndwich"],
      costForTwo: 40000,
      deliverytime: 36,
      avgRating: 6,
    },
  },
  {
    type: "restaurant",
    data: {
      id: "33457",
      name: "KFC",
      cloudinaryImageId: "bcdfefff",
      cusines: ["Burgers", "Biryani", "Fast Food", "SAndwich"],
      costForTwo: 40000,
      deliverytime: 36,
      avgRating: 3.6,
    },
  },
  {
    type: "restaurant",
    data: {
      id: "33458",
      name: "KFC",
      cloudinaryImageId: "bcdfefff",
      cusines: ["Burgers", "Biryani", "Fast Food", "SAndwich"],
      costForTwo: 40000,
      deliverytime: 36,
      avgRating: 3.6,
    },
  },
  {
    type: "restaurant",
    data: {
      id: "33459",
      name: "KFC",
      cloudinaryImageId: "bcdfefff",
      cusines: ["Burgers", "Biryani", "Fast Food", "SAndwich"],
      costForTwo: 40000,
      deliverytime: 36,
      avgRating: 3.6,
    },
  },
  {
    type: "restaurant",
    data: {
      id: "33458",
      name: "KFC",
      cloudinaryImageId: "bcdfefff",
      cusines: ["Burgers", "Biryani", "Fast Food", "SAndwich"],
      costForTwo: 40000,
      deliverytime: 36,
      avgRating: 5,
    },
  },
  {
    type: "restaurant",
    data: {
      id: "334567",
      name: "KFC",
      cloudinaryImageId: "bcdfefff",
      cusines: ["Burgers", "Biryani", "Fast Food", "SAndwich"],
      costForTwo: 40000,
      deliverytime: 36,
      avgRating: 3,
    },
  },
  {
    type: "restaurant",
    data: {
      id: "334557",
      name: "KFC",
      cloudinaryImageId: "bcdfefff",
      cusines: ["Burgers", "Biryani", "Fast Food", "SAndwich"],
      costForTwo: 40000,
      deliverytime: 36,
      avgRating: 2,
    },
  },
  {
    type: "restaurant",
    data: {
      id: "334556",
      name: "KFC",
      cloudinaryImageId: "bcdfefff",
      cusines: ["Burgers", "Biryani", "Fast Food", "SAndwich"],
      costForTwo: 40000,
      deliverytime: 36,
      avgRating: 1,
    },
  },
  {
    type: "restaurant",
    data: {
      id: "334523",
      name: "KFC",
      cloudinaryImageId: "bcdfefff",
      cusines: ["Burgers", "Biryani", "Fast Food", "SAndwich"],
      costForTwo: 40000,
      deliverytime: 36,
      avgRating: 4.6,
    },
  },
  {
    type: "restaurant",
    data: {
      id: "33453",
      name: "KFC",
      cloudinaryImageId: "bcdfefff",
      cusines: ["Burgers", "Biryani", "Fast Food", "SAndwich"],
      costForTwo: 40000,
      deliverytime: 36,
      avgRating: 4,
    },
  },
  {
    type: "restaurant",
    data: {
      id: "33452",
      name: "KFC",
      cloudinaryImageId: "bcdfefff",
      cusines: ["Burgers", "Biryani", "Fast Food", "SAndwich"],
      costForTwo: 40000,
      deliverytime: 36,
      avgRating: 4,
    },
  },
  {
    type: "restaurant",
    data: {
      id: "33451",
      name: "KFC",
      cloudinaryImageId: "bcdfefff",
      cusines: ["Burgers", "Biryani", "Fast Food", "SAndwich"],
      costForTwo: 40000,
      deliverytime: 36,
      avgRating: 4.6,
    },
  },
];
